
package com.aerolinea.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsAvion", targetNamespace = "http://webservice.aerolinea.com/", wsdlLocation = "http://localhost:46866/EjemploS1/wsAvion?wsdl")
public class WsAvion_Service
    extends Service
{

    private final static URL WSAVION_WSDL_LOCATION;
    private final static WebServiceException WSAVION_EXCEPTION;
    private final static QName WSAVION_QNAME = new QName("http://webservice.aerolinea.com/", "wsAvion");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:46866/EjemploS1/wsAvion?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSAVION_WSDL_LOCATION = url;
        WSAVION_EXCEPTION = e;
    }

    public WsAvion_Service() {
        super(__getWsdlLocation(), WSAVION_QNAME);
    }

    public WsAvion_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSAVION_QNAME, features);
    }

    public WsAvion_Service(URL wsdlLocation) {
        super(wsdlLocation, WSAVION_QNAME);
    }

    public WsAvion_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSAVION_QNAME, features);
    }

    public WsAvion_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsAvion_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsAvion
     */
    @WebEndpoint(name = "wsAvionPort")
    public WsAvion getWsAvionPort() {
        return super.getPort(new QName("http://webservice.aerolinea.com/", "wsAvionPort"), WsAvion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsAvion
     */
    @WebEndpoint(name = "wsAvionPort")
    public WsAvion getWsAvionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.aerolinea.com/", "wsAvionPort"), WsAvion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSAVION_EXCEPTION!= null) {
            throw WSAVION_EXCEPTION;
        }
        return WSAVION_WSDL_LOCATION;
    }

}
