
package com.aerolinea.cliente;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsAvion", targetNamespace = "http://webservice.aerolinea.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsAvion {


    /**
     * 
     * @param entity
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "remove", targetNamespace = "http://webservice.aerolinea.com/", className = "com.aerolinea.cliente.Remove")
    @Action(input = "http://webservice.aerolinea.com/wsAvion/remove")
    public void remove(
        @WebParam(name = "entity", targetNamespace = "")
        Avion entity);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "http://webservice.aerolinea.com/", className = "com.aerolinea.cliente.Count")
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://webservice.aerolinea.com/", className = "com.aerolinea.cliente.CountResponse")
    @Action(input = "http://webservice.aerolinea.com/wsAvion/countRequest", output = "http://webservice.aerolinea.com/wsAvion/countResponse")
    public int count();

    /**
     * 
     * @param id
     * @return
     *     returns com.aerolinea.cliente.Avion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://webservice.aerolinea.com/", className = "com.aerolinea.cliente.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://webservice.aerolinea.com/", className = "com.aerolinea.cliente.FindResponse")
    @Action(input = "http://webservice.aerolinea.com/wsAvion/findRequest", output = "http://webservice.aerolinea.com/wsAvion/findResponse")
    public Avion find(
        @WebParam(name = "id", targetNamespace = "")
        Object id);

    /**
     * 
     * @param entity
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "create", targetNamespace = "http://webservice.aerolinea.com/", className = "com.aerolinea.cliente.Create")
    @Action(input = "http://webservice.aerolinea.com/wsAvion/create")
    public void create(
        @WebParam(name = "entity", targetNamespace = "")
        Avion entity);

    /**
     * 
     * @return
     *     returns java.util.List<com.aerolinea.cliente.Avion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://webservice.aerolinea.com/", className = "com.aerolinea.cliente.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://webservice.aerolinea.com/", className = "com.aerolinea.cliente.FindAllResponse")
    @Action(input = "http://webservice.aerolinea.com/wsAvion/findAllRequest", output = "http://webservice.aerolinea.com/wsAvion/findAllResponse")
    public List<Avion> findAll();

    /**
     * 
     * @param entity
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "edit", targetNamespace = "http://webservice.aerolinea.com/", className = "com.aerolinea.cliente.Edit")
    @Action(input = "http://webservice.aerolinea.com/wsAvion/edit")
    public void edit(
        @WebParam(name = "entity", targetNamespace = "")
        Avion entity);

    /**
     * 
     * @param range
     * @return
     *     returns java.util.List<com.aerolinea.cliente.Avion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findRange", targetNamespace = "http://webservice.aerolinea.com/", className = "com.aerolinea.cliente.FindRange")
    @ResponseWrapper(localName = "findRangeResponse", targetNamespace = "http://webservice.aerolinea.com/", className = "com.aerolinea.cliente.FindRangeResponse")
    @Action(input = "http://webservice.aerolinea.com/wsAvion/findRangeRequest", output = "http://webservice.aerolinea.com/wsAvion/findRangeResponse")
    public List<Avion> findRange(
        @WebParam(name = "range", targetNamespace = "")
        List<Integer> range);

    /**
     * 
     * @param descripcion
     * @return
     *     returns java.util.List<com.aerolinea.cliente.Avion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarAviones", targetNamespace = "http://webservice.aerolinea.com/", className = "com.aerolinea.cliente.ConsultarAviones")
    @ResponseWrapper(localName = "consultarAvionesResponse", targetNamespace = "http://webservice.aerolinea.com/", className = "com.aerolinea.cliente.ConsultarAvionesResponse")
    @Action(input = "http://webservice.aerolinea.com/wsAvion/consultarAvionesRequest", output = "http://webservice.aerolinea.com/wsAvion/consultarAvionesResponse")
    public List<Avion> consultarAviones(
        @WebParam(name = "descripcion", targetNamespace = "")
        String descripcion);

}
